### ISSUE TITLE
JSON-LD: type column in json can be a single value or array - very hard to work with

### ISSUE THREAD

**Issue by pieterbos** [nuts-foundation/nuts-node#1213]
The type column in json responses from the nuts node can sometimes be a single value, or an array. At least for the post issuer/vc rest call, returning a VerifiableCredential. That works in theory, but causes several usability problems for using the nuts node as a developer:

1. Most openAPI generators usually will not generate correct code for this - it will just generate a list of strings, hopefully.
2. It's very hard to generate correct code for json to object mapping libraries, requiring hard to find annotations - if the json to object mapping library supports it at all.

This causes some developer annoyance and is time consuming.. This could be solved in a backwards compatible way, by always filling the response from the nuts node as an array, even if it is a single value. Perhaps in some next version it could always be made an array, making this easier to use.

**Comment by woutslakhorst** [comment]
Unfortunately it's JSON-LD and not JSON. 

The compaction of JSON-LD arrays with 1 value will yield that value and not an array. `type` is not the only field with that characteristic. Further more with some operations multiple credentials with different content can be returned (that's why credentialSubject has no type in OAS)

The idea we had to fix this is to allow for a custom context to be passed that can be used to project results to a fixed JSON schema of the callers choosing.

**Comment by reinkrul** [comment]
This could be solved using JSON-LD framing, which transforms document into a specified (JSON) format, e.g. with all singular values transformed into an array with a single value (when applicable). Question is, support this in Nuts node or task of integrating application.

@stevenvegt

**Comment by stevenvegt** [comment]
I will put it on the all-things-json-ld-list.

**Comment by woutslakhorst** [comment]
> This could be solved using JSON-LD framing

framing only changes the point of view, not the actual structure. Custom context would required for that.

**Comment by reinkrul** [comment]
This is known as array compaction, a feature of JSON-LD. VC data model v2 apparently removes this feature (source?). Thus when we fully embrace VC data model v2, this won't happen any more.

Until then we can always "uncompact" JSON-LD arrays in new APIs (e.g. VDR v2). We can't do that for the existing APIs, since that might break existing implementations assuming some fields are always a single value (e.g. `controller`).
