### ISSUE TITLE
Storage: decide and implement backup strategies

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1223]
https://github.com/nuts-foundation/nuts-node/pull/1189 introduced a storage configuration layer with a very basic backup feature (for the sake of being able to configure _something_). We need to decide what backup strategies we want to support, and implement them.

[woutslakhorst](https://github.com/woutslakhorst) https://github.com/nuts-foundation/nuts-node/pull/1189#discussion_r904948848

> I also added a note on the issue for this. I think Ops people configure DB backups differently (hourly/4hourly/daily) and how many to keep (auto-remove old), etc, etc. We can steal this from any other DB.
And to keep things simple: a cron expression instead of an interval. We can then use the expression to also name the backups. * * 4h 0 0 => backup_network_data_4hourly_20220623T120000.db

**Comment by gerardsn** [comment]
summary from this morning

Backup strategies
- backups are probably not something that should be managed by the nuts-node. Ops has their own process for this.
- bbolt is the exception since the db file will be locked by the nuts-node. This prevents an external backup regime and forces us to provide a backup mechanism.

Bbolt backups should be passed and handled by the nuts-node (not stoabs) to keep configuration simple. In a distributed network we cannot restore an older state, so allowing multiple backup intervals seems to be of limited value.
Config options: 
- to backup or not to backup (implied by interval?)
- backup interval
- how many backups to keep
- location?

**Comment by woutslakhorst** [comment]
Closing this for now. BBolt backups are possible. Future requirements will go in a new issue
