### ISSUE TITLE
Rebuild state based on transactions

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1506]
My node has a constant download of 400 kb/s while every node is up2date. Will have to find out which messages are sent. This is part of V5 release.

Cause: incorrect state in remote node DB. Caused by V3 problems.

Cure: Allow rebuilding off XOR and IBLT Trees based on transactions. This is an operation that has to iterate over all transactions and is thus quite heavy on the DB, memory and CPU.

**Comment by gerardsn** [comment]
https://github.com/nuts-foundation/performance-test/pull/4 should help with this

**Comment by woutslakhorst** [comment]
Also add check command

**Comment by gerardsn** [comment]
As stated in the original issue, the underlying problem that could result in an inconsistent State is already fixed and can only occur on nodes still running on V3. The nodes with issues are fixed, making the Rebuild command a solution for a hypothetical problem.

Closing this issue since 
- the problem can only occur on V3 nodes (Dropping data.db and restarting the node fixes the inconsistency. This relies on the other recipients of a private VC that was issued by this node for indexing of the given VC. (only indexing, actual VC is not lost))
- providing a full solution is rather complex (see linked PR), too complex for a problem that currently does not exist
- future functionality is likely to obsolete the feature
