### ISSUE TITLE
Validate service endpoint before adding to DID document

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1508]
When the receiving care organization's NutsComm endpoint is incorrect (in this case, it wasn't a valid reference to its vendor's NutsComm service), the eOverdracht sender can issue the `NutsAuthorizationCredential`, but the private transaction's payload never comes available at the receiving party.

The NutsComm endpoint in question was literally: `<vendor>?serviceType=eOverdracht-receiver` (so `<vendor>` instead of the DID).

A blocking error would be nice, but there should at least be an error in the logging.

Also consider tweaking the endpoint validating, so that we capture these kind of errors, since a `NutsComm` endpoint is either a gRPC endpoint or a reference.

**Comment by gerardsn** [comment]
It should not be possible to issue a private VC for a DID without a resolvable and valid NutsComm endpoint.

**Comment by woutslakhorst** [comment]
1 - yes for a syntax check on DID services
2 - Checking for validity of a VC at runtime is extremely dependant on the VC type. Which turns into a discussion on how. much of validation should be hardcoded.

**Comment by gerardsn** [comment]
I cannot reproduce the issue.

Even if I give both nodes an invalid NutsComm address:
```
"service": [
            {
                "id": "did:nuts:123abc",
                "serviceEndpoint": "%3Cvendor-did%3E/serviceEndpoint?type=NutsComm",
                "type": "NutsComm"
            }
        ],
```
`NutsAuthorizationCredentials` can be issued by, and resolved on both nodes. (I've tried master and v4.2.4 since this was latest tagged release at the time.) In the tests, private VC retrieval always works if 
1. there is a direct connection between involved nodes, 
2. the DID document contains a NutsComm service, doesn't matter if it is valid, and 
3. the node is restarted after creating a node DID to start the private VC scheduler.

If I remember the event correctly, restarting the node fixed some synchronization issues (node was ~10 tx behind and could no longer sync) and updating the NutsComm address allowed newly issued private VCs to be received, but private VCs issued prior to this correction were never received. 
- Condition 1: Not just the new, but all private VCs issued that week should have arrived if it was simply a connection issue.
- Condition 2: Does not cause any issues. 
- Condition 3: Most likely scenario by deduction. The node was not restarted -> private VC scheduler was not started -> scheduler never subscribed to private VC notifications -> after a restart the node did not know it had missed a private VCs...
- Option X: the node was already incapable of syncing with the network and might have been broken due to some completely unrelated issue. Perhaps related to #1236? (same party involved)

**Comment by gerardsn** [comment]
Should there be a way to reprocess all (unprocessed) private VCs?
Perhaps add an option to the notifier to just log events for processing after a restart? (not sure if it makes sense to have this option)

**Comment by gerardsn** [comment]
Currently didman performs some validation on compound services, but not on single services, and it is still possible to add invalid endpoints directly via the VDR.

Endpoint validation should be performed in the VDR by extending `validators.go`.  Endpoint validation should only be performed when an endpoint is added or updated from this node. DID updates received through the network should not be validated since this could break existing DIDs.
