### ISSUE TITLE
Core: Nuts node alters configuration in strict mode

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1699]
Should not do it: it should only check config, not alter it.

**Comment by woutslakhorst** [comment]
For the majority of config params this is true.

One example where it might not be true: API return body for access token request is empty in strictmode, but returns debug info when not in strictmode.

**Comment by gerardsn** [comment]
automatic behavior of the node:

1. IRMA server is changed to production mode. This is the only way to enable production mode.
2. CreateAccessToken on `/n2n/auth/v1/accesstoken` no longer returns details for an error msg. For good reasons, but can also be used to test if a node has strict mode enabled.
3. `internalratelimiter` is ignored _without_ a log message
4. `cpuprofile` is ignored with a log message
5. nodedid is no longer automatically detected. Log messages explaining the status and consequences of the nodedid are clear.

Last two point are not a problem and point 3 can be fixed by adding a simple log message. Any thoughts on points 1 and 2?

**Comment by gerardsn** [comment]
Also see [read the docs](https://nuts-node.readthedocs.io/en/latest/pages/deployment/configuration.html#strict-mode) for documentation on strict mode.

**Comment by woutslakhorst** [comment]
All mentioned features will be deprecated. Won't fix.
