### ISSUE TITLE
Describe technical details on API security V2

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1896]
A vendor should be able to use different type of keys, generated with different tools and should still be able to configure the authorized_keys file. It should also be able to implement JWT generation.

- [x] Point to the spec of the authorized_keys file format
- [x] Explain how non-ssh keys can be added to the authorized_keys file
- [x] Point to the specification of the SHA256 ssh fingerprint
- [x] Explain how to generate the ssh fingerprint for any type of key
- [x] Explain on how to use ssh tools to help in all of the points above
- [x] Add an example on a openssl generated key pair that is added to authorized_keys and used in code.
- [x] Add example audit log messages to documentation
- [x] Fix API authentication docs layout

**Comment by beardedfoo** [comment]
@woutslakhorst regarding " Explain how to generate the ssh fingerprint for any type of key"

I have documented this for PEM and JWK formatted keys using the RSA, ECDSA, and Ed25519 algorithms, which are the only algorithms we support.

* Do you feel PEM and JWK is enough or are there other file types that we should document the process for?
* Is it enough to assume people will figure out converting their keys in other fomats to PEM or JWK in order to use them with nuts?
* Do we want to support anything other than PEM and JWK for the `nuts-jwt-generator -i /path/to/keyfile --export-authorized-key` command?

**Comment by woutslakhorst** [comment]
PEM will already cover 99%. Especially when we also provide examples for generation of keys using ssh and openssl

**Comment by stevenvegt** [comment]
Index contains sub headers of the article
<img width="295" alt="Screenshot 2023-02-20 at 09 45 17" src="https://user-images.githubusercontent.com/3896736/220056188-ee87d3f0-31d4-4422-ba9d-e4b21cfe07de.png">

**Comment by stevenvegt** [comment]
Documentation is still a bit messy. Did you try generating it locally?
https://nuts-node.readthedocs.io/en/latest/pages/integrating/api-authentication.html
