### ISSUE TITLE
HTTP: CORS headers don't seem to work

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2256]
Unit test asserts "Vary: Origin", but this is not a CORS header.

**Comment by eattevelt** [comment]
Situation:
Public YIVI url hosted on different domain dan the hosting application.
After starting YIVI dialog an error occurs.
Console log reveals CORS issue. No header set.
The used NUTS config is:
`http:
  default:
    address: :1323
  alt:
    public:
      address: :1323
      cors:
        origin:
          - host.example.com`
The returned response on request GET /public/auth/irmaclient/session/PsJUABvCyISbVeNBoKQU/status is as expected but missing CORS headers:
![afbeelding](https://github.com/nuts-foundation/nuts-node/assets/136798346/8d1fe27e-0198-4522-9c0f-4c2b1dda4e2a)


Temp workaround:
Added extra response headers on Ingress that worked:
`access-control-allow-origin: https://host.example.com
access-control-allow-credentials: true
access-control-allow-methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
access-control-max-age: 1728000`
Possibly only the access-control-allow-origin is needed.

**Comment by woutslakhorst** [comment]
You need to do an OPTIONS request with an `Origin` header to debug

**Comment by eattevelt** [comment]
@reinkrul Will investigate. It is all Yivi code, so we don't call the status endpoint ourselves.
Our Yivi code is possibly outdated. Maybe it will fix the issue...
For now the workaround still works...
