### ISSUE TITLE
Increase vault http client timeout

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2316]
to 5s by default.
also possibly in vault proxy?

**Comment by reinkrul** [comment]
Hashicorp Vault Proxy uses default config (=60s). It can be configured using Vault client config properties (e.g. env variables).

But the vault proxy having a larger (default) time-out it doesn't make much sense; the more since we don't pass the request context there, meaning it doesn't get cancelled in case the request context in the Nuts node gets cancelled (due to time-out).

So, proposed changes:
- Pass HTTP request context to Vault client calls to propagate cancellations
- Increase default client time-out in Nuts-node to 5s
- The same for the client time-out in the vault proxy

**Comment by reinkrul** [comment]
"good first issue"

**Comment by woutslakhorst** [comment]
or connect it to a general http client timeout setting? "better first issue"

**Comment by gerardsn** [comment]
both timeouts are configurable, request contexts are propagating to the client calls
