### ISSUE TITLE
did:jwk support

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2349]
If the nuts node needs to support issuing credentials to wallets, it must support did:jwk resolution.
Spec: https://github.com/quartzjer/did-jwk/blob/main/spec.md

Since the did identifier determines the public key, this should't be that hard.

**Comment by reinkrul** [comment]
Why must it support it for issuing credentials to wallets? `did:key` doesn't support key rotation or revocation/deletion, so pretty unsafe for long(er)-term usage.

**Comment by woutslakhorst** [comment]
wallets won't do key rotation, they'll just use another key for each credential

**Comment by reinkrul** [comment]
Did some work on did:key a while back, maybe we could use it; https://github.com/reinkrul/golang-didkey

**Comment by reinkrul** [comment]
Basically just involves implementing VDR's `Resolver` interface (only `Resolve`, not `ResolveControllers` since did:jwk doesn't support additional controllers). Actual integration in the Nuts node (using them) involves switching to the right resolver depending on method of the subject DID, but that also applies to did:web and did:key support (so out of scope for this issue).

**Comment by beardedfoo** [comment]
Fixed by https://github.com/nuts-foundation/nuts-node/pull/2380 ?
