### ISSUE TITLE
Set assurance_level to low by default

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#2378]
Currently the assurance level from IRMA is determined by evaluating the `digidlevel` value. If this level is missing or unknown the `assurance_level` in the access_token is empty. This is confusing. We should either consider an empty level as an invalid credential, or we treat it as the lowest level. I would argue for the latter, since we know and trust the issuer (gemeente Nijmegen).

Background:
The problem occurred when someone who used a demo credential and filled in the English word "substantial" instead of the dutch "substantieel".

**Comment by reinkrul** [comment]
As the IRMA attribute is issued by a qualified issuer, I don't see reason to change it when mapping the IRMA attribute. But since the self-signed means contract is not issued by a qualified issuer, maybe we should just pass on whatever is passed? And/or validate it upfront, when it is issued. Defaulting to low is probably a safe choice, but might be equally confusing as well.

**Comment by woutslakhorst** [comment]
It should be treated as the lowest level by the verifier, not by our code. I would not set values on things that are outside of our control.
