### ISSUE TITLE
New root endpoint for new OAuth2 APIs

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2439]
The current `/public` is ugly and leads to longer paths than necessary, since `/public` doesn't have a functional indicator what is actually under it (other than the classification/intended access). This is unconventient especially for Web DIDs; they become long like:

```
did:web:example.com:public:identity:(some-id)
```

Having classification in a public API is also an API-antipattern i.m.o. So I propose the following; move everything DID/OAuth2 related to `/iam` ("I Am", "Identity and Authn/Authz Management"), so:

```
did:web:example.com:iam:(some-id)
https://example.com/iam/(some-id)/metadata.xml
https://example.com/iam/(some-id)/token
https://example.com/iam/(some-id)/credential
https://example.com/iam/(some-id)/authorize

etc
```

Authentication means callbacks might not fit under the `/iam` path, but the existing ones might be reworked anyways given the move towards verifiable credentials. So they can either fit under `/iam` or get a new publicly accessible root path.

**Comment by gerardsn** [comment]
I agree with a new path. I'm also fine with `/id/...` or `/identity/...` since to me it just indicates that the next path segment is an identifier. `iam` on the other hand has a well defined meaning that probably doesn't match everything we are going to add to this. Considering we already have some endpoints on `/n2n/identity`, we should probably use `/identity` for consistency.

---

We currently have a strong coupling between the APs and the modules their business logic resides in (API `/internal/module/...` lives in `module` package and is defined in OAPI spec `module_v*.yaml`). This makes it easier to handle large changes/refactors within modules by introducing a new spec version, and it was/is fine for internal APIs anyway.

Currently most "public" communication happens on the nuts-network and up to now we have only 2 document public endpoints (1*/public and 1*/n2n). Now that we are moving the node2node communication away from the network towards API calls, I think we should also rethink the API structure for public facing APIs.

Since the new API paths will be focused around `identities` and probably require multiple modules it no longer makes sense to push all these paths into our module oriented OAPI specifications. So, I propose to also add a new module to handle these public facing APIs. This is a high-level API that depends on all other modules for the business logic and has very little of its own, like didman. 

Versioning on these API's is probably less relevant since we implement international standards. So the implementation is either correct or it isn't. If there are newer versions available of the standard, the version to use is negotiated through announcing supported protocols in the client and server metadata.

**Comment by reinkrul** [comment]
We decided on `/iam`
