### ISSUE TITLE
VDR: Support did:web DID with root domain

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2833]
Currently, we only support subpaths (`/iam/1234`), but we know some wallets (MS Authenticator) only support did:web root DIDs (`example.com/.well-known/did.json`) for security reasons. We should support this.

**Comment by woutslakhorst** [comment]
Pretty much essential when using the nuts-node as issuer. Clarification on how the API paths for the 'root' DID relate to the current iam ones.

**Comment by reinkrul** [comment]
Current paths:
- Resolving did:web: `/iam/{id}/did.json`
- AS metadata: `/.well-known/oauth-authorization-server/iam/{id}`
- OAuth2 endpoints: `/iam/{id}/authorize` (and `/token`, etc)

**Comment by gerardsn** [comment]
Do we need to change all paths, or only allow `.well-known`s on the root? The well-knowns serve the metadata where all other endpoints are found. 

It's not the nicest solution, but could be a temporary quick fix to make the MS Authenticator work and gives us time to figure out the other questions. Since all other endpoints come from the metadata it should be possible to change the endpoint without migration issues.

**Comment by woutslakhorst** [comment]
In addition to gerardsn's comment, what if we put the {did} in the paths and not iam/{id}? Root DIDs can than use the same methods.

**Comment by reinkrul** [comment]
> In addition to gerardsn's comment, what if we put the {did} in the paths and not iam/{id}? Root DIDs can than use the same methods. Only metadata and did.json need to be served from an exact location?

Probably the cleanest solution if we don't want to replicate all OAuth2/OpenID endpoints. Leads to longer endpoints, but it'll also work for non-did:web DIDs (should we need it in the future).
