### ISSUE TITLE
Change holder APIs to wallet APIs

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2841]
In the past month we've added APIs for wallet functionality on `/internal/vcr/v2/holder/{did}/vc[/{id}]`. I think it might be better to change path segment `/holder/` to `/wallet/` to clarify that they are operating on a specific wallet, and not the vcr as a whole.

Thoughts?

(The proposal does not include /internal/vcr/v2/holder/{did}/vp that has been around a lot longer)

**Comment by reinkrul** [comment]
I think consistency with `/internal/vcr/v2/holder/{did}/vp` is more important.

I can imagine `holder` and `wallet` might become separate concepts, a holder might have multiple wallets? Or maybe we call it 'user' by then.

**Comment by gerardsn** [comment]
`/internal/vcr/v2/holder/{did}/vp` is a weird API to me since it is basically a signing request that does some sanity checks to make sure the result is valid. I'm not even sure it's that useful since it validates all VCs in the VP, which fails if this contains VCs from non did:nuts issuers or if the node is missing some contexts. Is this currently used??

Considering that the description for all APIs reads "do ... with wallet" and that the holder package no longer contains a holder object, it sounds like we might need to make the transition everywhere to simplify the mental model. It is not a pressing issue, so I will add to the V6 milestone so we can decide on this before the next release.

**Comment by reinkrul** [comment]
Discussed with @gerardsn;

Why keep it as 'holder':
- Holder adheres to the 3 roles in the VC model (holder/verifier/issuer), diverging from that could be confusing
- We have another 'holder' endpoint, which we can't change, so endpoints would then diverge

Why change it:
- We generally talk about 'wallets', not holders. So 'wallet' would be easier to understand.
- Given the endpoints work on a specific DID (actually, `/holder/vp` does not), you could reason `wallet equals a single DID` (and vice versa), so renaming it to wallet would make sense. A "holder" could hold multiple wallets. But then again, nobody enforces a single DID to a single wallet (you could have a wallet with VCs issued to different DIDs, which are all yours).

We decided to keep it, because we value consistency over potential (semantic) correctness.
