### ISSUE TITLE
VCR: implement full-text search for Verifiable Credentials

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#300]
A user-friendly user interface might allow searching for a substring of e.g. the name of a care organization. We currently only support searching for the start of the string (name in this instance), while a user could expect to be searching full-text.

We need to decide whether we need this and/or whether this is a feature for the Nuts Node (or another service).

**Comment by woutslakhorst** [comment]
A phonetic search like "Cologne Phonetic" might work. This is an algorithm that converts string to numbers

A simple test:

"Because we care bv" transforms to 14834713
"Bekos we ker beevee" transforms to 14834713
"Bekos we cer beevee" transforms to 14838713

The first 2 match exactly while the third almost matches. A binary based index would easily find results. This could be combined with levenshtein distance in a post-processing step.

**Comment by woutslakhorst** [comment]
More results using different algorithms:

```
Cologne
Because we care bv transforms to 14834713
Bekos we ker beevee transforms to 14834713
Bekos we cer beevee transforms to 14838713
Sensire transforms to 8687
Zenziere transforms to 8687
Soundex
Because we care bv transforms to B261
Bekos we ker beevee transforms to B261
Bekos we cer beevee transforms to B261
Sensire transforms to S526
Zenziere transforms to Z526
Metaphone
Because we care bv transforms to BKSWKRBF
Bekos we ker beevee transforms to BKSWKRBF
Bekos we cer beevee transforms to BKSWSRBF
Sensire transforms to SNSR
Zenziere transforms to SNSR
```

**Comment by reinkrul** [comment]
🚀
