### ISSUE TITLE
IAM: Token Introspection Response does not contain `aud` claim

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3036]
Probably not good?

**Comment by gerardsn** [comment]
It depends...

[RFC7662](https://datatracker.ietf.org/doc/html/rfc7662) contains the following cryptic description from 
> aud
      OPTIONAL.  Service-specific string identifier or list of string
      identifiers representing the intended audience for this token, as
      defined in JWT [[RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)].

I find [this](https://www.ory.sh/docs/hydra/guides/audiences) more helpful
> There are two types of audience concepts in OAuth 2.0 and OpenID Connect:
>
>OAuth 2.0 access token audience: OAuth 2.0 access tokens are "internal-facing". In other words, the aud claim of an OAuth 2.0 access token defines the endpoints at which the token can be used.
OpenID Connect ID token audience: OpenID Connect ID tokens are "external-facing". The aud claim of an OpenID Connect ID Token defines which clients should accept it.

We are in the OAuth flow and are using internal facing tokens, so `aud` should contain a (list of) resource URL that this token grants access to. This decision is left to the PDPs, so I think the nuts node should not contain/provide this information.

**Comment by reinkrul** [comment]
But it does need to return it in the token introspection response, so the PDP can act on it?

**Comment by gerardsn** [comment]
I don't think this information is ever communicated to the node. IMO it's also not needed since this decision is delegated to the policy backend. The only thing the policy backend needs to know is if the vp_token is enough to grant access to the resource currently requested. If we were to send a resource ACL from the policy engine to the node, we're back in the same situation as with the NutsAuthzCreds where the node is used to administer this. 

We've also had some discussion on where the decision is made what resources a token grants access to. Normally this is before the token is issued, but it was/is? unclear where the patient is communicated. If this is in the authorization request, you could potentially leak what patients are in your care by sending different responses to an authz request based on 'knowing' the patient. There is no standardised way to provide additional information about the requested resource (patient) during the token request, so if not decided during the authz request, the only other option (I know of) is an on the spot decision during the resource request. I don't know what the current state on this discussion is though...

**Comment by woutslakhorst** [comment]
The token is currently not scoped to resources only scopes. I vote for closing the issue for now
