### ISSUE TITLE
Helm charts won't start container due to gid/uid and datadir change (from /opt/nuts/data to /nuts/data/)

### ISSUE THREAD

**Issue by rolandgroen** [nuts-foundation/nuts-node#3040]
The nuts node from the helm charts fails with 

```
Could not start the server" error="unable to configure Crypto: mkdir /opt/nuts/data/crypto: permission denied
```

Which makes sense since the datadir of the nuts node has implicitly changed (./data):
```
RUN adduser -D -H -u 18081 nuts-usr
USER 18081:18081
WORKDIR /nuts
```
The default for datadir is ./data, so the value becomes /nuts/data, as documented in [docs/pages/deployment/docker.rst](https://nuts-node.readthedocs.io/en/latest/pages/deployment/docker.html).

**Comment by rolandgroen** [comment]
I think we can split up two groups of problems: 

1. The directories have changed.
2. The guid and uid of the nuts process has changed from root to 18081.

I suggest we'll tackle nr 2. first.

**Comment by rolandgroen** [comment]
For reference, this issue is caused by: Docker: don't run as root user (#2917)

**Comment by gerardsn** [comment]
#2917 did not change any existing default directory. It did change the default working directory to `/nuts`. Most examples used `/opt/nuts` but in reality `/` was the working directory inside the container. This was undocumented, so this change should have little to no impact, and can always be overridden by the config.

The permission issue in the helm chart is fixed by the linked PR, so I'm closing this issue.
