### ISSUE TITLE
Discovery Service: add seed to detect service reset

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3463]
During the hackathon the discovery server was reset causing the clock to be reset. Subscribers to the service could not detect the reset. Clients would not receive any updates because the clock value in their request was higher than that of the Server.

Yes, this is a misbehaving server, so the use-case should switch to a different server. But the new server could suffer from the same issue since the service is no longer in sync.

I propose to let the server treat any received clock value higher that its own, the same as having not received a clock value. This should let most issues resolve itself.

**Comment by woutslakhorst** [comment]
> I propose to let the server treat any received clock value higher that its own, the same as having not received a clock value. This should let most issues resolve itself.

This could still result in a different state due to timing issues. Also, when switching to another server, if the service_id does not change, the clients will also not update.

We could add a seed next to each service_id. If it changes due to a reset or switch to a different server, it can be detected and the clients can reset.
