### ISSUE TITLE
Missing newlines at end of status/diagnostics

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#36]
annoying when using curl and cli

**Comment by reinkrul** [comment]
I was fixing this but then realized this is a UI problem due to the way it's represented to the user (you). I'd say if this is a problem when using `curl`, pipe it through "echo" which'll add (or can) add a trailing newline. CLI doesn't support diagnostics a.t.m., but should add a newline at the end because it is a UI.

**Comment by woutslakhorst** [comment]
ok
