### ISSUE TITLE
VCR: Allow searching for exact matches

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#386]
Before `go-leia` allowed partial, phonetical searches, only exact matches on VC fields would yield results. Now it's the other way around, only partial matches yield results. Given an organization concept with name "Fort Pannerden", searching for "fort" or "Pannerden" yields it as result but searching for "Fort Pannerden" doesn't.

Both should be supported.

**Comment by woutslakhorst** [comment]
The index config (see yaml file in assets) defines a `whitespace` tokenizer. A new tokenizer can be defined (using leia.Tokenizer func def). Instead of tokenizing:

`"A B C"` as `["A", "B", "C"]`

it should tokenize as:

`"A B C"` as `["A", "B", "C", "A B C"]`, adding `A B C` as extra result.

(lowercase transformer remains the same)
