### ISSUE TITLE
Implement dynamic service discovery

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#690]
Using RFC015 `NutsComm` endpoints.

**Comment by woutslakhorst** [comment]
New/Updated DID docs should be tracked for new/discarded addresses.

**Comment by woutslakhorst** [comment]
See #701 for first part

**Comment by reinkrul** [comment]
Would be nice to have before end of 2022 (eOverdracht production release), but not required.

**Comment by reinkrul** [comment]
In log on dev:

```
time="2023-02-24T17:59:15+01:00" level=warning msg="Failed to open gRPC stream" error="call answered by other node DID than expected" module=Network peerAddr="nuts-development.woutslakhorst.nl:5555" protocolVersion=2
```

(Node is bootstrap node)

**Comment by reinkrul** [comment]
Connection management changed such that a second connection with an existing peer ID may exist, but that may be an attacker (since peer ID is not authenticated). But the message senders select receiver connections only on peer ID, thus the response message might be sent to the attacker.

Should be fixed by sending response messages to the connection it was received on.

This issue does not exist in v5 or earlier (newly introduced).

**Comment by reinkrul** [comment]
@gerardsn  Add integration test with "stolen" peer ID to assess what happens?

**Comment by gerardsn** [comment]
@reinkrul see https://github.com/nuts-foundation/nuts-node/pull/1938 for the test
