### ISSUE TITLE
Nats stream design

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#759]
In our pursuit to use Nats for various events, there are some Nats Jetstream concepts that require a little bit of design.
Basically there are producers, consumers, streams and servers. All have lots of options to consider. This issue is about the choices for the streams.

Streams are defined as the storage settings of the event system. Each stream has its own storage options. Multiple events can be grouped on a stream if they have the same requirements for storage (and still then, it's an option to do it different). Events in the Nuts node are to be used to decouple engines better and to enable events to flow from the node to other systems. Based on those requirements, two main streams can be identified:

- TRANSACTIONS containing events with and without payload in various states throughout the system.
- DATA containing VC's and DID Documents that can be used for service discovery or can trigger external systems.

Based on the limited knowledge, these streams can have the following config:

- Storage: File
- MaxAge: one week (retention based on time rather than size)

Any downtime longer than a week would require a *replay* of transactions from storage!
Streams MUST be available before producers and consumers connect. The event engine could register required streams from the `Start()` method.

Nats documentation on streams: https://docs.nats.io/nats-concepts/jetstream/streams

**Comment by dmeijboom** [comment]
> Multiple events can be grouped on a stream

Streams consume NATS subjects which means that all messages sent to the subject will be captured by the stream. So it would be nice to also add an overview of subjects per stream. 

> Based on the limited knowledge, these streams can have the following config:
>
> Storage: File
> MaxAge: one week (retention based on time rather than size)

This makes sense.

> Streams MUST be available before producers and consumers connect. The event engine could register required streams from the Start() method.

Probably the `Configure()` method right? Not sure because the NATS server wouldn't be started yet but if we do this in the `Start()` method other engines would somehow have to wait before the streams are created. Either way it might be good to think of another way to setup the NATS stuff then we did before.

**Comment by woutslakhorst** [comment]
> Probably the Configure() method right? Not sure because the NATS server wouldn't be started yet but if we do this in the Start() method other engines would somehow have to wait before the streams are created. Either way it might be good to think of another way to setup the NATS stuff then we did before.

One of the ideas of using events it to get a less tight coupling between engines. This would mean that when the event engine is started as one of the first engines, we will be ok. Others will be started later and will be able to use the fully started Nats server and registered streams.

**Comment by woutslakhorst** [comment]
A consumer also has a wide range of config possibilities.

The proposal is to use a single consumer per engine (for now). The durable name for the consumer is the engine name.
The ack policy will be AckExplicit.
The DeliverPolicy will be DeliverLast (eg continue where left)
The FilterSubject will be something like DATA.VerifiableCredential or DATA.DIDDocument or DATA.* (or something with transactions)
The DeliverySubject is not used since this is for worker queues (clustering)
MaxDeliver will be set to 10 (if nacked and something was weird, try again but not unlimited)
ReplayPolicy is ReplayInstant

**Comment by reinkrul** [comment]
> The DeliverPolicy will be DeliverLast (eg continue where left)
`DeliverPolicy` is only applicable when new consumers are created:

> When a consumer is first created, it can specify where in the stream it wants to start receiving messages.

I'd say consumers are never created newly after the initial startup, and since we don't retain all of history in the NATS stream, newly introduced consumers (say we introduce an `AUdit` engine which wants to log everything that happens in NATS), we'll have to replay the DAG. So I'd say `DeliverNew` would be the most applicable.
