### ISSUE TITLE
Specify properties for `CredentialSubject` in OpenAPI schema

### ISSUE THREAD

**Issue by joepeding** [nuts-foundation/nuts-node#814]
In the [Nuts Verifiable Credential API spec (v1)](https://nuts-node.readthedocs.io/en/latest/_static/vcr/v1.yaml), the schema for CredentialSubject is listed as:
```
    CredentialSubject:
      type: object
      description: Subject of a Verifiable Credential identifying the holder and expressing claims.
```

This is inconvenient when generating code because it makes it hard to use the CredentialSubject and the `resources` it contains (also not specified in the schema).

**Comment by woutslakhorst** [comment]
You can also add "undefined" credentials.... which is ideal for hackathons. It allows for adding functionality without changing the code and contract.

**Comment by reinkrul** [comment]
@joepeding since it's arguably not part of the Nuts API spec (though part of the RFC), we didn't yet decide whether and how it should be part of it (maybe in JSON-LD-compatible JSON schemas?).

For the time being, I wrote them up in OpenAPI format here: https://github.com/reinkrul/java-nuts-client/blob/main/specs/credentials.yaml

(part of Nuts java client library)
