### ISSUE TITLE
Clustering/Cloud support

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#877]
Umbrella-issue for supporting clustered Nuts node and making it _cloud native_

**Comment by jarimayenburg** [comment]
One of the issues I ran into is that the Nuts node is unable to run in multiple instances (pods in k8s) if they share the same volume for the data directory (same thing for the demo EHR). The node will hang on the third log-line
```
time="2022-03-15T10:38:05Z" level=info msg="Starting server"
time="2022-03-15T10:38:05Z" level=info msg="Build info: \nGit version: master\nGit commit: cb642704cafdcd89a918537559b8a3f2d86a800e\nOS/Arch: linux/amd64\n"
time="2022-03-15T10:38:05Z" level=info msg="Config: \nauth.clockskew -> 5000\nauth.contractvalidators -> [irma uzi dummy]\nauth.http.timeout -> 30\nauth.irma.autoupdateschemas -> true\nauth.irma.schememanager -> pbdf\nauth.publicurl -> https://node.hinq.ht.hinq.nl\nconfigfile -> /opt/nuts/nuts.yaml\ncrypto.storage -> fs\ncrypto.vault.address -> \ncrypto.vault.pathprefix -> kv\ncrypto.vault.token -> \ndatadir -> /data\nevents.nats.hostname -> localhost\nevents.nats.port -> 4222\nevents.nats.storagedir -> \nevents.nats.timeout -> 30\nhttp.default.address -> :1323\nhttp.default.cors.origin -> []\nloggerformat -> text\nnetwork.bootstrapnodes -> node.lumc.ht.hinq.nl:31555\nnetwork.certfile -> /pki/tls.pem\nnetwork.certkeyfile -> /pki/tls.key\nnetwork.disablenodeauthentication -> false\nnetwork.enablediscovery -> true\nnetwork.enabletls -> true\nnetwork.grpcaddr -> :5555\nnetwork.nodedid -> \nnetwork.truststorefile -> /pki/ca.pem\nnetwork.v1.advertdiagnosticsinterval -> 5000\nnetwork.v1.adverthashesinterval -> 2000\nnetwork.v1.collectmissingpayloadsinterval -> 60000\nnetwork.v2.gossipinterval -> 5000\nstrictmode -> false\nvcr.overrideissueallpublic -> true\nverbosity -> info\n"
```

The PVC that the datadir is on has access mode ReadWriteMany and they're run on a storage class that supports this mode. It seems that the already started node has a lock on a file in that directory and the second node is waiting for that file to become available.

To sketch the usecase: we currently have no need to horizontally scale the Nuts nodes, this is more for performing rolling releases. Currently because of this issue we have to use a "recreate" release strategy, which first kills the currently running node and then starts the new one. To avoid downtime, that's not ideal.

**Comment by reinkrul** [comment]
Azure

**Comment by woutslakhorst** [comment]
The current DB (bbolt) has a lock on the file. This is by design since it's a memory mapped file.

**Comment by reinkrul** [comment]
We now have Redis support and parties are running it on Azure. Clossing issue.
