### ISSUE TITLE
Discussion: how to apply JSON-LD features

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#902]
Items:

- Validate VCs (and optionally DIDs) when creating them, checking there are no fields that are not specified in the context
- Do we want to store VC fields that are not present in the context?
- Do we want to represent DID documents as JSON-LD as well?

**Comment by woutslakhorst** [comment]
- allow adding custom context for search capabilities (OAS code gen)

**Comment by woutslakhorst** [comment]
Given the following problems:

- valid context config mapping
- context downloading
- JSON-LD searching challenges due to poor graph DB support
- Backwards compatibility problems due to signature generation algorithm
- API content-types
- Cognitive complexity (people want to search on type)
- Lots of code

And benefits/features we actively use:

- none

We really have to think about cancelling future support of JSON-LD and switch to SD-JWT

**Comment by reinkrul** [comment]
I don't see us leveraging the graph-capability of JSON-LD in credentials; it only makes sense if the existing ecosystem already uses linked data or RDF (which it doesn't).

**Comment by woutslakhorst** [comment]
closing, will pop up when JSON-LD becomes important
