### ISSUE TITLE
Auth: return full VCs instead of VC IDs in token introspection response

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#911]
The current API requires subsequent calls after token introspection to resolve the actual VCs, which IDs are returned in the introspection response. The response could include the full VCs, to eliminate the subsequent calls.

**Comment by woutslakhorst** [comment]
I think it might have been kept simple due to unknowns. What if the holder added a credential which isn't available in the VCR? A p2p out-of-band type credential.

We could just add another JWT property with resolved credentials. So if a credential wasn't resolved it's not in there. Adding a property also means we don't have to do it now for V1.

**Comment by reinkrul** [comment]
> I think it might have been kept simple due to unknowns. What if the holder added a credential which isn't available in the VCR? A p2p out-of-band type credential.

The access token is created from the bearer token (or directly using VPs) so the VCs are known to the Nuts Node, although it might not administer the 3rd party (non-Nuts, out-of-band) credentials. Thus, it wouldn't be able to resolve it anyways.

**Comment by reinkrul** [comment]
Also see https://github.com/nuts-foundation/nuts-node/issues/450
