### ISSUE TITLE
Network: test protocol v2

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#958]
Define test cases, implement them in some way.

**Comment by woutslakhorst** [comment]
I'd like a complex case:

- 20+ nodes, each node with it's own TX behaviour (none, burst, constant, branching, etc)
- random network behaviour for all connections (slow downs, disconnects, etc)
- partial mesh
- run for X time, compare diagnostics every Y. Reset after Z
- Live monitoring

Then the question would be: on what hardware? Web accessible (due to remote working)? Debugging? Quite some work.

**Comment by woutslakhorst** [comment]
A specific case can be to have two nodes, set the gossip interval quite large. Have each node publish 200 TXs (over the gossip limit). Wait a while then compare.

**Comment by woutslakhorst** [comment]
nuts-foundation/nuts-go-e2e-test#18 adds a gossip overflow test.
